### ISSUE TITLE
Get a bug

### ISSUE THREAD

**Issue by Amir33851** [fahadmahmood8/stock-locations-for-woocommerce#144]
On cart page stock price not updating it get's regular price can you help with this

**Comment by Amir33851** [comment]
yes, the checkbox is enabled and I am trying with a simple product.

**Comment by fahadmahmood8** [comment]
Ok, I will check it and come back to you.

**Comment by Amir33851** [comment]
https://palmbattery.com/product/this-is-test-product/
please check this

**Comment by fahadmahmood8** [comment]
Dear Amir,

I have checked the issue in details, it is not a bug but this feature is not available in the basic version, please check the settings page for the following option.

**Display stock location price instead of default product/variation price** _It will display stock location prices with location names as well._

You will clearly see the tag against this feature as "premium feature". I am closing this topic as the feature is working as expected if you are using the advanced version.
