### ISSUE TITLE
stock not saving

### ISSUE THREAD

**Issue by dennebar** [fahadmahmood8/stock-locations-for-woocommerce#149]
When i enter stock to a product and update. It will be 0 every time after updating. 
Can you help me resolve this issue?

**Comment by fahadmahmood8** [comment]
You are missing the enable/disable toggle button on every stock location edit page, please check and confirm if your issue get resolved?

**Comment by dennebar** [comment]
Perfect! thanks for the quick reply! Great plugin for when i open my second flowershop!

**Comment by dennebar** [comment]
Even an update to the plugin! thanks!

**Comment by LynksenDymytrii** [comment]
Hi @fahadmahmood8! Thank you for the plugin!
Just experienced the same problem, and would never have guessed it myself if it wasn't your reply here.
Never realized freshly created locations are disabled by default.

Maybe a good idea would be to not display the disabled locations in the product location stock settings?
Or render them as disabled. Otherwise, it might be extremely not obvious to detect

**Comment by fahadmahmood8** [comment]
I agree with you, actually there was a user who asked me to do this. Sometimes people are very picky, you can understand how many tickets I am resolving and on wordpress.org separately. Every other user comes up like he found a bug and I have to fix it. Nobody tries to understand the situation that this plugin is evolving. I have given multiple tabs too but most of the users don't even explore the plugin completely. Toggle button can be unnoticed but eye icon is a kind of self explanatory under the locations tab on the settings page. Anyways, I am trying my best to make the things understandable.
