### ISSUE TITLE
Allow editing location values on orders after being reduced

### ISSUE THREAD

**Issue by alexmigf** [fahadmahmood8/stock-locations-for-woocommerce#90]
Currently is not possible to edit the location value after the order reduced the stocks.

Forums topic: https://wordpress.org/support/topic/edit-stock-after-complete-order/?view=all#post-14256093

**Comment by pacmanito** [comment]
This one is a very important feature cause many store owners would use automatic stock allocation but from time to time change the allocation manually due to some reasons. Now to do that we need to change the order status to pending and back to processing which can result in many unwanted consequences (the most obvious one is emails sent to buyers).

**Comment by joaoaviz** [comment]
Is this feature ever coming ? 
im willing to pay for the premium but im afraid it wont do exactly what i need, do you have a free trial ?

**Comment by fahadmahmood8** [comment]
New version has been released with this feature, video attached as a demo https://www.youtube.com/embed/Q1Lq-cbv2hE
